### ISSUE TITLE
API key link is broken

### ISSUE THREAD

**Issue by arctouch-stellalunardeli** [Q42/Q42Stats.Android#32]
Hey there;

While trying to access the "[The API project](https://github.com/Q42/accessibility-pipeline/tree/main/api)" link listed under the "Usage" section, I've received a 404 error message. 
Can you please verify?

Thank you.
Stella Lunardeli.

**Comment by arctouch-benogilvie** [comment]
@arctouch-stellalunardeli I suspect the correct link is https://github.com/Q42/accessibility-data-pipeline/tree/main/api ... @huijkman can you confirm?

**Comment by jorisbr** [comment]
https://github.com/Q42/accessibility-data-pipeline/tree/main/api is indeed the correct link. Feel free to shoot me a message if you have any questions regarding the data pipeline and API.

**Comment by jorisbr** [comment]
It took some time till I had the appropriate rights for this repo to fix this in the reamde. https://github.com/Q42/Q42Stats.Android/commit/d655e6c76068d3a24eae1a19dddd0dd8cf237d6d
